# render.yaml

databases:
  - name: mybbs_db
    databaseName: mybbs
    user: mybbs_user
    plan: free #　追加箇所

services:
  - type: web
    name: my-flask-bbs
    env: python
    buildCommand: "pip install -r requirements.txt && python -c 'from app_10 import db, app; with app.app_context(): db.create_all()'
    startCommand: "gunicorn app_10:app" # ★app_10に変更
    plan: free
    healthCheckPath: /
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: mybbs_db
          property: connectionString