databases:
  - name: mybbs_db
    databaseName: mybbs
    user: mybbs_user
    plan: free

services:
  - type: web
    name: my-flask-bbs
    env: python
    # ★★★ 最終的にシンプルなコマンドに戻します ★★★
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app_10:app"
    plan: free
    healthCheckPath: /
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: mybbs_db
          property: connectionString